### ISSUE TITLE
对海康威视摄像头使用基本用法里的代码，XML解析报错

### ISSUE THREAD

**Issue by duskNNNN** [zhuovi/XiaoFeng.Onvif#8]
仅修改ip，port，user，pass，并且在海康威视后台已开启ONVIFi协议，请大佬指点
![image](https://github.com/zhuovi/XiaoFeng.Onvif/assets/94543546/e29cf631-6d56-4d6a-b0e9-10c7c113c61f)

**Comment by zhuovi** [comment]
先把获取到的xml文件内容发出来  按这个提示应该是 内容不对

**Comment by fc200** [comment]
![image](https://github.com/zhuovi/XiaoFeng.Onvif/assets/75766479/5f946752-03a3-4801-b60b-043f33c1d517)  我是获取设备信息的时候有错误，下载源码看了一下是返回了404

**Comment by fc200** [comment]
![image](https://github.com/zhuovi/XiaoFeng.Onvif/assets/75766479/6149dd14-2bf8-4ac2-bb1c-6541990e8c3c)
直接使用示例也是解析错误 @zhuovi

**Comment by fc200** [comment]
![image](https://github.com/zhuovi/XiaoFeng.Onvif/assets/75766479/7e1e9e60-537f-4bee-8571-fddf95b4907e)
![image](https://github.com/zhuovi/XiaoFeng.Onvif/assets/75766479/a82b9fdf-d267-45fd-84c8-a34fb7cc2456)

楼主出现错误的原因大概是端口、用户名、密码不对，能复现，我这里是能探测到设备、能获取到时间，就是获取设备信息出现404 @duskNNNN @zhuovi

**Comment by duskNNNN** [comment]
感谢各位帮助，确实是输入信息搞错了
